name: Build OctoFX

on:
  push:
    branches: [ "main" ]
  workflow_dispatch:

jobs:  
  build:    
    runs-on: windows-2019
    
    steps:      
      - uses: actions/checkout@v2
      
      - name: Setup MSBuild
        uses: microsoft/setup-msbuild@v1

      - name: Setup NuGet
        uses: NuGet/setup-nuget@v1.0.5

      - name: Navigate to Workspace
        run: |
          cd $GITHUB_WORKSPACE
        
      - name: Create Build Directory
        run: mkdir _build

      - name: Restore Packages
        run: nuget restore source/OctoFX.sln

      - name: Build Solution
        run: |
          msbuild.exe "source/OctoFX.sln" /nologo /nr:false /p:DeployOnBuild=true /p:DeployDefaultTarget=WebPublish /p:WebPublishMethod=FileSystem /p:DeleteExistingFiles=True /p:platform="Any CPU" /p:configuration="Release" /p:PublishUrl="../_build"
      
      - name: Create Zip Package for Octopus Deploy
        # You may pin to the exact commit or the version.
        # uses: OctopusDeploy/create-zip-package-action@4e6bb23129c1cc5e337d1f74a200abba63de4b62
        uses: OctopusDeploy/create-zip-package-action@v3.0.2
        with:
          # Package Id.
          package_id: "OctoFX_GHA"
          # Package version.
          version: "0.0.1"
          # The folder to put the resulting package in, relative to the current working directory; not the base path.
          output_folder: "./packaging"
          # The base path for the input files.
          base_path: "source/_build"
          # Multi-line list of files to include in the package, relative to the basePath. Supports globbing.
          files: |
            **/*.*
