name: Build OctoFX

on:
  push:
    branches: [ "main" ]
  workflow_dispatch:

jobs:  
  build:    
    runs-on: windows-2019
    
    steps:      
      - uses: actions/checkout@v2
      
      - name: Setup MSBuild
        uses: microsoft/setup-msbuild@v1

      - name: Setup NuGet
        uses: NuGet/setup-nuget@v1.0.5

      - name: Navigate to Workspace
        run: |
          cd $GITHUB_WORKSPACE
        
      - name: Create Build Directory
        run: mkdir _build

      - name: Restore Packages
        run: nuget restore source/OctoFX.sln

      - name: Build Solution
        run: |
          #msbuild.exe "source/OctoFX.sln" /nologo /nr:false /p:DeployOnBuild=true /p:DeployDefaultTarget=WebPublish /p:WebPublishMethod=FileSystem /p:DeleteExistingFiles=True /p:platform="Any CPU" /p:configuration="Release" /p:PublishUrl="../_build"
          msbuild.exe "source/OctoFX.sln" /nologo /nr:false /p:SkipInvalidConfigurations=true /p:PackageLocation="../_build" /p:RunOctoPack=true /p:OctoPackPackageVersion="0.0.2" /p:OctoPackPublishPackageToFileShare="./packaging" /p:OctoPackEnforceAddingFiles=true /p:platform="Any CPU" /p:configuration="Release"
          #/p:DeployOnBuild=true /p:DeployDefaultTarget=WebPublish /p:WebPublishMethod=FileSystem /p:DeleteExistingFiles=True /p:platform="Any CPU" /p:configuration="Release" /p:PublishUrl="../_build"
      
      - name: What's in here
        run: dir
      
      - name: Create Zip Package for Octopus Deploy
        uses: OctopusDeploy/create-zip-package-action@v3.0.2
        with:
          package_id: "OctoFX_GHA"
          version: "0.0.1"
          output_folder: "./packaging"
          base_path: "source/_build"
          files: |
            **/*.*
            
      - name: Push Package to Octopus Deploy
        uses: OctopusDeploy/push-package-action@v3.0.4
        with:
          packages: packaging/*.zip
          overwrite_mode: OverwriteExisting
          api_key: ${{ secrets.OCTOPUS_API_KEY }}
          server: 'https://demo.octopus.app'
          space: 'Enterprise'
